---
AWSTemplateFormatVersion: 2010-09-09

Description: 'Stack to deploy a highly available, elastic, scalable simple webserver environment
  hosting "hexGL" which a game resembling wipeout.
  This master template will reference other templates of "concerns".
  hexGL - http://hexgl.bkcore.com'

Metadata:

  Authors:
    Description: James Radtke (jaradtke@amazon.com)  
  License:
    Description: 'This is based on the reference architecture created by:
    Darryl Osborne (darrylo@amazon.com) 
    https://github.com/aws-samples/aws-refarch-wordpress
    I was unable to grok his complete work, so I have been "stepping in to it" using portions of 
    his example.'

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - EC2KeyName
        - SshAccessCidr
        - UseRoute53Boolean
        - AppDomainName
        - AppName
    - Label:
        default: Network
      Parameters:
        - NumberOfAZs
        - AvailabilityZones
        - VpcCidr
        - VpcTenancy
        - PublicSubnet0Cidr
        - PublicSubnet1Cidr
        - PublicSubnet2Cidr
        - PublicSubnet3Cidr
        - PublicSubnet4Cidr
        - PublicSubnet5Cidr
        - WebSubnet0Cidr
        - WebSubnet1Cidr
        - WebSubnet2Cidr
        - WebSubnet3Cidr
        - WebSubnet4Cidr
        - WebSubnet5Cidr
    - Label:
        default: Bastion Tier
      Parameters:
        - BastionInstanceType
    - Label:
        default: Web Tier
      Parameters:
        - PublicAlbAcmCertificate
        - PHPVersion
        - WebInstanceType
        - WebAsgMax
        - WebAsgMin
    ParameterLabels:
      BastionInstanceType:
        default: Bastion Instance Type
      AppDomainName:
        default: Domain for this application (cloudxabide.com)
      AppName:
        default: App Alias for URL (hexGL)
      EC2KeyName:
        default: EC2 Key Pair
      PublicAlbAcmCertificate:
        default: ALB Certificate ARN
      SshAccessCidr:
        default: SSH Access From
      UseRoute53Boolean:
        default: DNS record set (Route53)
      WebAsgMax:
        default: Web ASG Max
      WebAsgMin:
        default: Web ASG Min
      WebInstanceType:
        default: Web Tier Instance Type
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      VpcCidr:
        default: VpcCidr
      VpcTenancy:
        default: VpcTenancy
      PHPVersion:
        default: PHP Version
      PublicSubnet0Cidr:
        default: Public Subnet 0
      PublicSubnet1Cidr:
        default: Public Subnet 1
      PublicSubnet2Cidr:
        default: Public Subnet 2
      PublicSubnet3Cidr:
        default: Public Subnet 3
      PublicSubnet4Cidr:
        default: Public Subnet 4
      PublicSubnet5Cidr:
        default: Public Subnet 5
      WebSubnet0Cidr:
        default: Web Subnet 0
      WebSubnet1Cidr:
        default: Web Subnet 1
      WebSubnet2Cidr:
        default: Web Subnet 2
      WebSubnet3Cidr:
        default: Web Subnet 3
      WebSubnet4Cidr:
        default: Web Subnet 4
      WebSubnet5Cidr:
        default: Web Subnet 5

Parameters:

  BastionInstanceType:
    AllowedValues:
    - t2.nano 
    - t2.micro 
    - t2.small 
    - t2.medium 
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.nano
    Description: Bastion EC2 instance type.
    Type: String
  EC2KeyName:
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair. Your bastion & Web instances will launch with this KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
  PHPVersion:
    AllowedValues:
    - 5.5
    - 5.6
    - 7.0
    Default: 7.0
    Description: The version of PHP to install.
    Type: String 
  PublicAlbAcmCertificate:
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: '[ Optional ] The AWS Certification Manager certificate ARN for the ALB certificate - this certificate should be created in the region you wish to run the ALB and must reference the hexGL domain name you use below.'
    Type: String
  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0
  UseRoute53Boolean:
    AllowedValues:
      - true
      - false
    Default: true
    Description: Specifies whether a record set should be created in Route 53 for your WordPress domain name.
    Type: String
  WebAsgMax:
    AllowedPattern: ^((?!0$)[1-2]?[0-9]|30)$
    ConstraintDescription: Must be a number between 1 and 30.
    Default: 4
    Description: Specifies the maximum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebAsgMin:
    AllowedPattern: ^([0-0]?[0-9]|10)$
    ConstraintDescription: Must be a number between 0 and 10.
    Default: 2
    Description: Specifies the minimum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebInstanceType:
    AllowedValues:
      - t2.nano 
      - t2.micro 
      - t2.small 
      - t2.medium 
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.small
    Description: The Amazon EC2 instance type for your web instances.
    Type: String
  AppDomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: 'The domain name used in the URL creation'
    Type: String
  AppName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: 'The hostname used in the URL creation'
    Type: String
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note:
      The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of Availability Zones to use in the VPC. This must match your
      selectiont in the list of Availability Zones parameter.
    Type: Number
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
  VpcTenancy:
    AllowedValues:
    - default
    - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
  PublicSubnet0Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.200.0/24
    Description: CIDR block for Public subnet 0 located in Availability Zone 0
    Type: String
  PublicSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.201.0/24
    Description: CIDR block for Public subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.202.0/24
    Description: CIDR block for Public subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.203.0/24
    Description: CIDR block for Public subnet 3 located in Availability Zone 3
    Type: String
  PublicSubnet4Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.204.0/24
    Description: CIDR block for Public subnet 4 located in Availability Zone 4
    Type: String
  PublicSubnet5Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.205.0/24
    Description: CIDR block for Public subnet 5 located in Availability Zone 5
    Type: String
  WebSubnet0Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/22
    Description: CIDR block for Web subnet 0 located in Availability Zone 0
    Type: String
  WebSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.4.0/22
    Description: CIDR block for Web subnet 1 located in Availability Zone 1
    Type: String
  WebSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.8.0/22
    Description: CIDR block for Web subnet 2 located in Availability Zone 2
    Type: String
  WebSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.12.0/22
    Description: CIDR block for Web subnet 3 located in Availability Zone 3
    Type: String
  WebSubnet4Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.16.0/22
    Description: CIDR block for Web subnet 4 located in Availability Zone 4
    Type: String
  WebSubnet5Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.20.0/22
    Description: CIDR block for Web subnet 5 located in Availability Zone 5
    Type: String

Conditions:

  AvailableAWSRegion:
    !Or [
      !Equals [ !Ref 'AWS::Region', us-east-1 ],
      !Equals [ !Ref 'AWS::Region', us-east-2 ],
      !Equals [ !Ref 'AWS::Region', us-west-1 ],
      !Equals [ !Ref 'AWS::Region', us-west-2 ]
    ]
  CreateRecordSet: !And
    - !Equals [ true, !Ref UseRoute53Boolean ]
    - !Condition AvailableAWSRegion

Resources:

  bastion:
    Condition: AvailableAWSRegion
    DependsOn: [ hexvpc, securitygroups ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BastionInstanceType:
          !Ref BastionInstanceType
        BastionSecurityGroup:
          !GetAtt [ securitygroups, Outputs.BastionSecurityGroup ]
        EC2KeyName:
          !Ref EC2KeyName
        NumberOfSubnets:
          !Ref NumberOfAZs
        Subnet:
          !GetAtt [ hexvpc, Outputs.PublicSubnet ]
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-03-bastion.yaml
  hexvpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NumberOfAZs:
          !Ref NumberOfAZs
        AvailabilityZones:
          !Join
            - ','
            - !Ref AvailabilityZones
        VpcCidr:
          !Ref VpcCidr
        VpcTenancy:
          !Ref VpcTenancy
        PublicSubnet0Cidr:
          !Ref PublicSubnet0Cidr
        PublicSubnet1Cidr:
          !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr:
          !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr:
          !Ref PublicSubnet3Cidr
        PublicSubnet4Cidr:
          !Ref PublicSubnet4Cidr
        PublicSubnet5Cidr:
          !Ref PublicSubnet5Cidr
        WebSubnet0Cidr:
          !Ref WebSubnet0Cidr
        WebSubnet1Cidr:
          !Ref WebSubnet1Cidr
        WebSubnet2Cidr:
          !Ref WebSubnet2Cidr
        WebSubnet3Cidr:
          !Ref WebSubnet3Cidr
        WebSubnet4Cidr:
          !Ref WebSubnet4Cidr
        WebSubnet5Cidr:
          !Ref WebSubnet5Cidr
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-01-hexvpc.yaml
  publicalb:
    Condition: AvailableAWSRegion
    DependsOn: [ hexvpc, securitygroups ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NumberOfSubnets:
          !Ref NumberOfAZs
        Subnet:
          !GetAtt [ hexvpc, Outputs.PublicSubnet ]
        PublicAlbAcmCertificate:
          !Ref PublicAlbAcmCertificate
        PublicAlbSecurityGroup:
          !GetAtt [ securitygroups, Outputs.PublicAlbSecurityGroup ]
        Vpc:
          !GetAtt [ hexvpc, Outputs.Vpc ]
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-03-publicalb.yaml
  route53:
    Condition: CreateRecordSet
    DependsOn: [ publicalb, web ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DnsEndpoint:
          !GetAtt [ publicalb, Outputs.PublicAlbDnsName ] 
        DnsHostId:
          !GetAtt [ publicalb, Outputs.PublicAlbCanonicalHostedZoneId ] 
        AppDomainName:
          !Ref AppDomainName
        AppName:
          !Ref AppName
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-05-route53.yaml
  securitygroups:
    Condition: AvailableAWSRegion
    DependsOn: hexvpc
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SshAccessCidr:
          !Ref SshAccessCidr
        Vpc:
          !GetAtt [ hexvpc, Outputs.Vpc ]
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-02-securitygroups.yaml
  web:
    Condition: AvailableAWSRegion
    DependsOn: [ hexvpc, publicalb, securitygroups ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KeyName:
          !Ref EC2KeyName
        NumberOfSubnets:
          !Ref NumberOfAZs
        PHPVersion:
          !Ref PHPVersion
        PublicAlbTargetGroupArn:
          !GetAtt [ publicalb, Outputs.PublicAlbTargetGroupArn ]
        PublicAlbHostname:
          !GetAtt [ publicalb, Outputs.PublicAlbHostname ]
        SslCertificate:
          !GetAtt [ publicalb, Outputs.SslCertificate ]
        WebAsgMax:
          !Ref WebAsgMax
        WebAsgMin:
          !Ref WebAsgMin
        WebInstanceType:
          !Ref WebInstanceType
        WebSecurityGroup:
          !GetAtt [ securitygroups, Outputs.WebSecurityGroup ]
        Subnet:
          !GetAtt [ hexvpc, Outputs.WebSubnet ]
      TemplateURL: https://s3.amazonaws.com/cloudxabide/aws-cloudformation-hexgl/templates/aws-hexgl-04-web.yaml

Outputs:

  StackStatus:
    Description: Master Stack Status
    Value: !If [ AvailableAWSRegion, !Join [ '', [ 'Stack created in an available region: ', !Ref 'AWS::Region' ] ], "!!ERROR!!! - Nothing to do! - unavailable AWS Region. You must create this stack in an available AWS Region: 'us-east-1', 'us-east-2', 'us-west-2', 'eu-west-1', 'ap-southeast-2'." ]
